### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'blinker._saferef'

### ISSUE THREAD

**Issue by gh0sti** [klept0/MS-Rewards-Farmer#101]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

[selenium-wire: How to resolve No module named blinker._saferef](https://www.marekrost.cz/selenium-wire-how-to-resolve-blinker-saferef)
kvě
01
2024
Out of nowhere all of our Python projects that utilize selenium-wire suddenly stopped working when redeployed. It turns out that selenium-wire is no longer maintained as of January 2024 and the project depends on package blinker, specifically file blinker._saferef that is no longer available in latest blinker versions 1.8.0 and 1.8.1.

The solution is to add direct dependency on blinker<1.8.0 into your project in order to prevent selenium-wire from automatically downloading the latest blinker version.

https://www.marekrost.cz/selenium-wire-how-to-resolve-blinker-saferef

### Copy and paste your error

ModuleNotFoundError: No module named 'blinker._saferef'

### Screenshots

AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\optmanager.py", line 9, in <module>
    import blinker._saferef

### Value of dashboard variable

AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\optmanager.py", line 9, in <module>
    import blinker._saferef

**Comment by klept0** [comment]
I thought I just rolled that back and I didn't see dependabot updated it. I will roll it back and make that version the version to use. Thanks for the notification and let me know if you see any other issues.

**Comment by klept0** [comment]
rolled back and pinned version - closing this issue as resolved

**Comment by Gaboros** [comment]
Still not working. I think it should be blinker==1.7.0 not blinker>=1.7.0 because it's still pulling 1.8.x.
