### ISSUE TITLE
[BUG] Mobile not working

### ISSUE THREAD

**Issue by gh0sti** [klept0/MS-Rewards-Farmer#102]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

When the script gets to Mobile points it stops and errors out trying to read the browser version.

### Copy and paste your error

cannot read browser version

### Screenshots

no screenshot

### Value of dashboard variable

Just the mobile site having issues I am wondering if we need a new agent string?

**Comment by OmegaBlurz** [comment]
temp workaround is using -v to manually get the mobile searches to actually start, whats weird to me is that this bug isnt happening on all pcs I use the script on, not sure why

**Comment by Ices-Eyes** [comment]
I think it should be related to the change from quit to close on the closeBrowser function in the latest commit of browser.py... Haven't time to check atm, but started for me after that change...

**Comment by gh0sti** [comment]
doing -v works which is odd that headless won't work. So as of now headless won't work for my setup.

**Comment by klept0** [comment]
Pushed a fix - was checking out the issues with UD Chromedriver - give it a shot and let me know if this resolves your issue

**Comment by RobertMochnacky** [comment]
Hi,

reference to the VersusGame still present in main.py...
