### ISSUE TITLE
Is it possible to add the Discord webhook integration again?

### ISSUE THREAD

**Issue by yourfriendaaron** [klept0/MS-Rewards-Farmer#105]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

The Discord integration from Charles's script was very useful. Is it possible to add that back in? Thanks!

### Copy and paste your error

n/a

### Screenshots

n/a

### Value of dashboard variable

n/a

**Comment by klept0** [comment]
Apprise was put in place to allow you to use multiple different notification options - please have a look at the readme if you did not prior to opening this.
