### ISSUE TITLE
[Feature] Change the notification message

### ISSUE THREAD

**Issue by agustinscaz** [klept0/MS-Rewards-Farmer#122]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

I think it would be a good feature to implement adding the Points Earned Today in the notification messages (Telegram, Discord...).

![image](https://github.com/klept0/MS-Rewards-Farmer/assets/17032561/af0af428-64b6-4a0e-89a1-e8a7d82dcb2f)

So the notification should have that information:

Daily Points Update
👤 Account: whatever@gmail.com
⭐️ Points earned today: 9,00
💰 Total points: 11.440,00

### Copy and paste your error

N/A

### Screenshots

N/A

### Value of dashboard variable

N/A

**Comment by klept0** [comment]
This is already a feature....I am not sure what you are asking for. You can see the exact thing you pasted at line 272 or so in main.py

**Comment by agustinscaz** [comment]
I mean that "Points earned today" info is wrong... I don't earn 9 points today... y earn 187.

The message would be like:
Daily Points Update
👤 Account: [whatever@gmail.com]
⭐️ Points earned in last execution: 9,00
⭐️ Points earned today: 187,00
💰 Total points: 11.440,00
