### ISSUE TITLE
[BUG] driver.quit causing previous issue of hanging process with heavy load on cpu

### ISSUE THREAD

**Issue by Guido30** [klept0/MS-Rewards-Farmer#136]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

in browser.py
```
def getChromeVersion(self) -> str:
        chrome_options = ChromeOptions()
        chrome_options.add_argument("--headless=new")
        chrome_options.add_argument("--no-sandbox")
        driver = WebDriver(options=chrome_options)
        version = driver.capabilities["browserVersion"]

        driver.quit()

        return version
```

Is causing the previously reported and now known issue of leaving the chrome process open with high cpu usage
i tested running it with the close method instead and seems to work fine

### Copy and paste your error

no terminal error

### Screenshots

no screenshot

### Value of dashboard variable

dashboard not involved

**Comment by cal4** [comment]
Fixed for me after some changes in #137, lemme know if it works for you and can make a hotfix branch to master.
