### ISSUE TITLE
[BUG] Read to earn bring you on a trip

### ISSUE THREAD

**Issue by Ices-Eyes** [klept0/MS-Rewards-Farmer#141]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

If you use the latest read to earn feature for a couple of day, rewards will start stating you are on a trip, and hence disable the rewards page. I'm not sure if this is country related or what (Italy here). And I'm not sure if it could depend on the US value used on the country attribute on the json data in the read to earn file. 

### Copy and paste your error

Since you are on a trip, anything goes on errore since the reward page is completely disabled

### Screenshots

N/A

### Value of dashboard variable

N/A

**Comment by fdotcico** [comment]
Same as me (located in Italy too)

**Comment by SteveeeeeS** [comment]
i had this, but i the next day i forced the script to GB and it was fixed for me.

**Comment by weltonbraga** [comment]
Same problem here. I'm from Brazil
![449757219_980508033861887_4701648244445252114_n](https://github.com/klept0/MS-Rewards-Farmer/assets/29134217/185b1488-52b7-40ed-bfc2-072858e78b1b)

**Comment by weltonbraga** [comment]
For me, this change solves the problem:
```python
# json data to confirm an article is read
json_data = {
    "amount": 1,
    # "country": "us",
    "country": self.browser.localeGeo,
    "id": 1,
    "type": 101,
    "attributes": {
        "offerid": "ENUS_readarticle3_30points",
    },
}
```

**Comment by klept0** [comment]
Check to see if the new release resolves your issue
