### ISSUE TITLE
Title MFA login stack

### ISSUE THREAD

**Issue by inlfwetrust** [klept0/MS-Rewards-Farmer#147]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Branch

master

### Commit

N/A

### Describe the bug

My account has MFA enabled
After this:
2024-07-15 15:40:05,350 [INFO] [LOGIN] Writing password...
I am getting notification to approve the log-in
It shows this
2024-07-15 15:40:12,555 [INFO] [LOGIN] No email proof, all clear
and does not progress further

When I run it with -V it shows that the page just stack on the MFA page.
If I open another tab and login manually, restart it works until the session is expired.

### Copy and paste your error

2024-07-15 15:39:50,911 [INFO] [LOGIN] Logging-in...
2024-07-15 15:40:00,896 [INFO] [LOGIN] Entering email...
2024-07-15 15:40:05,350 [INFO] [LOGIN] Writing password...
2024-07-15 15:40:12,555 [INFO] [LOGIN] No email proof, all clear

### Screenshots

![image](https://github.com/user-attachments/assets/d29efcc6-e767-490c-a35a-b01706fdb297)

### Value of dashboard variable

N/A

**Comment by inlfwetrust** [comment]
I did some tests and it turned out this option is culprit of the issue in browser.py
`options.add_argument("--blink-settings=imagesEnabled=false")`
removing this option resolves the issue

**Comment by klept0** [comment]
Added a note to the browser.py file for others just in case - thank you for the input
