### ISSUE TITLE
TimeoutException BUG

### ISSUE THREAD

**Issue by 4RDev** [klept0/MS-Rewards-Farmer#183]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Title

- [X] The title is no longer "Title" and I edited it with the right error name.

### Branch

master

### Commit

idk

### Describe the bug

i use python main.py -v, but error like this!

### Copy and paste your error

←[38;5;39m2024-08-17 00:54:24,732 [INFO] ********************xxxxxxxx@outlook.com********************←[0m
←[38;21m2024-08-17 00:54:24,732 [DEBUG] in __init__←[0m

DevTools listening on ws:/0000.0.0.1:0000/devtools/browser/00000a-19ce-0000-afeb-000000
←[38;5;39m2024-08-17 00:54:36,110 [INFO] Screen size: 1275x1090←[0m
←[38;5;39m2024-08-17 00:54:36,183 [INFO] Device size: 1220x939←[0m
←[38;21m2024-08-17 00:54:36,336 [DEBUG] out __init__←[0m
←[38;21m2024-08-17 00:54:36,337 [DEBUG] in __enter__←[0m
←[38;5;39m2024-08-17 00:54:58,936 [INFO] [LOGIN] Logging-in...←[0m
←[38;21m2024-08-17 00:55:09,159 [DEBUG] in __exit__ exc_type=<class 'selenium.common.exceptions.TimeoutException'> exc_value=Message:
Stacktrace:
Backtrace:
        (No symbol) [0x01036643]
        (No symbol) [0x00FCBE21]
        (No symbol) [0x00ECDA9D]
        (No symbol) [0x00F01342]
        (No symbol) [0x00F0147B]
        (No symbol) [0x00F38DC2]
        (No symbol) [0x00F1FDC4]
        (No symbol) [0x00F36B09]
        (No symbol) [0x00F1FB76]
        (No symbol) [0x00EF49C1]
        (No symbol) [0x00EF5E5D]
        GetHandleVerifier [0x012AA142+2497106]
        GetHandleVerifier [0x012D85D3+2686691]
        GetHandleVerifier [0x012DBB9C+2700460]
        GetHandleVerifier [0x010E3B10+635936]
        (No symbol) [0x00FD4A1F]
        (No symbol) [0x00FDA418]
        (No symbol) [0x00FDA505]
        (No symbol) [0x00FE508B]
        BaseThreadInitThunk [0x76C66A24+36]
        RtlInitializeExceptionChain [0x778FAA6F+143]
        RtlInitializeExceptionChain [0x778FAA3A+90]
 traceback=<traceback object at 0x0000000C0009BAC0>←[0m
←[38;5;196m2024-08-17 00:55:11,229 [ERROR] ←[0m
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\newms22\msajah\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
  File "C:\Users\Administrator\Downloads\newms22\msajah\main.py", line 236, in executeBot
    Login(desktopBrowser, args).login()
  File "C:\Users\Administrator\Downloads\newms22\msajah\src\login.py", line 29, in login
    self.executeLogin()
  File "C:\Users\Administrator\Downloads\newms22\msajah\src\login.py", line 35, in executeLogin
    self.utils.waitUntilVisible(By.ID, "i0116")
  File "C:\Users\Administrator\Downloads\newms22\msajah\src\utils.py", line 62, in waitUntilVisible
    return WebDriverWait(self.webdriver, timeToWait).until(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x01036643]
        (No symbol) [0x00FCBE21]
        (No symbol) [0x00ECDA9D]
        (No symbol) [0x00F01342]
        (No symbol) [0x00F0147B]
        (No symbol) [0x00F38DC2]
        (No symbol) [0x00F1FDC4]
        (No symbol) [0x00F36B09]
        (No symbol) [0x00F1FB76]
        (No symbol) [0x00EF49C1]
        (No symbol) [0x00EF5E5D]
        GetHandleVerifier [0x012AA142+2497106]
        GetHandleVerifier [0x012D85D3+2686691]
        GetHandleVerifier [0x012DBB9C+2700460]
        GetHandleVerifier [0x010E3B10+635936]
        (No symbol) [0x00FD4A1F]
        (No symbol) [0x00FDA418]
        (No symbol) [0x00FDA505]
        (No symbol) [0x00FE508B]
        BaseThreadInitThunk [0x76C66A24+36]
        RtlInitializeExceptionChain [0x778FAA6F+143]
        RtlInitializeExceptionChain [0x778FAA3A+90]

←[38;5;39m2024-08-17 00:55:11,662 [INFO] [POINTS] Data saved for the next day.←[0m

### Screenshots

python main.py -v

### Value of dashboard variable

test

**Comment by Yarmash10** [comment]
I got past this bit by changing: login.py -> line 45 -> from: isTwoFactorEnabled: bool = False; to: isTwoFactorEnabled: bool = True

Unfortunately I experienced further TimeoutException errors after getting logged in so I've reverted to the old script.

**Comment by 4RDev** [comment]
> I got past this bit by changing: login.py -> line 45 -> from: isTwoFactorEnabled: bool = False; to: isTwoFactorEnabled: bool = True
> 
> Unfortunately I experienced further TimeoutException errors after getting logged in so I've reverted to the old script.

:(, help me pleaseee

**Comment by cal4** [comment]
Try develop branch to see if above fixes your issue
