### ISSUE TITLE
Option to notify only successful summary

### ISSUE THREAD

**Issue by Guido30** [klept0/MS-Rewards-Farmer#194]
An option in the config.yaml like the following example would only notify when the script successfully runs until the end for that account
```
apprise:
  summary: ON_SUCCESS
```
The current options don't allow to only notify successful executions of the script but will always contain any crashes or runtime errors on the python side
```
ON_ERROR
ALWAYS
NEVER
```

**Comment by cal4** [comment]
`ALWAYS` is equivalent to this. This config only applies to the apprise summary email. Exceptions and the like will always be sent via Apprise (assuming the config exists).

But, if this isn't wanted, run the script with the [`--disable-apprise` flag](https://github.com/klept0/MS-Rewards-Farmer#:~:text=%2Dda/%2D%2Ddisable%2Dapprise%20disables%20Apprise%20notifications%20for%20the%20session%2C%20overriding%20config.yaml.%20Useful%20when%20running%20manually%20as%20opposed%20to%20on%20a%20schedule.). Useful when manually executing and don't need async notifications.

**Comment by Guido30** [comment]
"Exceptions and the like will always be sent via Apprise" thats what my suggestion would avoid, ON_SUCCESS would skip notifying any exception, its ok if this is not achievable, thanks anyways

**Comment by cal4** [comment]
Oh it's definitely possible, probably would be best to put it under a different config key though. The summary only covers the results sent after a run. Exceptions are bubbled up and sent as soon as they occur. 

Either way, doable but this key isn't the best place for this
