### ISSUE TITLE
how do i setup the config-private.yaml

### ISSUE THREAD

**Issue by coolareeb** [klept0/MS-Rewards-Farmer#212]
how do i setup the config-private.yaml : # config-private.yaml
# Copy this file to config-private.yaml to use
apprise:
  urls:
    - 'discord://WebhookID/WebhookToken'  # Replace with your actual Apprise service URLs

**Comment by klept0** [comment]
https://github.com/klept0/MS-Rewards-Farmer/blob/develop/CHANGELOG.md
