### ISSUE TITLE
There needs to be more time between searches, and possibly start of searches

### ISSUE THREAD

**Issue by leem919** [klept0/MS-Rewards-Farmer#213]
**Is your feature request related to a problem? Please describe.**
Yes. Searches often don't count.

**Describe the solution you'd like**
Microsoft recently added a new rule only allowing 3 searches to count for points between 15-minute periods. Searches should be changed to account for that. Some of the tasks that are completed before that part also seem to count towards searches, so maybe a 15-minute wait should be placed between when search automations start.

**Describe alternatives you've considered**
I've tried using a chrome extension or other bots to complete searches, but they all seem to have similar problems.

**Additional context**
Some accounts or regions may not be impacted by this, so a possible solution there could be to include a toggle.

**Comment by klept0** [comment]
You can edit the time between searches - read the config and edit it accordingly.
