### ISSUE TITLE
The dev branch does not support Brazilian Portuguese.

### ISSUE THREAD

**Issue by Willian-Massao** [klept0/MS-Rewards-Farmer#214]
pycontry not have suport for pt-br, if forces in code bypass the problem

**Comment by klept0** [comment]
Did you change the config file as instructed in the change log?

**Comment by EspaimH** [comment]
Assuming you're using the developer branch, you can workaround it if you change line 41 in browser.py to
`self.localeLang, self.localeGeo = self.getLanguageCountry("pt_BR", "BR")`
That's just a temporary solution though, I think.
