### ISSUE TITLE
[Help needed] Raspberry Pi - 'Unsupported platform' & 'NoSuchDriverException'

### ISSUE THREAD

**Issue by 28Black** [klept0/MS-Rewards-Farmer#216]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

0f0052c

### Describe the bug

Hi, I recently got a Raspberry Pi (Raspberry Pi 5 Model B Rev 1.0) and am trying to get the script running on it. I am relatively new to the Linux ecosystem and need your help.
About the system (latest Raspberry Pi OS): 

> PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
> NAME="Debian GNU/Linux"
> VERSION_ID="12"
> VERSION="12 (bookworm)"
> VERSION_CODENAME=bookworm
> ID=debian

After having researched and tried a few things, I am currently at the following stage:

- I have cloned the script to my Pi and customized accounts,json
- installed chromedriver (`sudo apt install chromium-chromedriver`) and copied it to the user area (`cp /usr/bin/chromedriver /home/xx/.local/share/undetected_chromedriver/chromedriver_copy`)
- created a virtual environment and successfully installed all requirements there
- edited the browser.py to point to the copied chromedriver so that it can be patched. Lines 109 to 115 now look like this for me:

```
driver = webdriver.Chrome(
            options=options,
            seleniumwire_options=seleniumwireOptions,
            user_driver_executable_path="/home/xx/.local/share/undetected_chromedriver/chromedriver_copy",
            data_dir=self.userDataDir.as_posix(),
            version_main=major,
        )
```
Unfortunately, when I run the script, I get the error message below.

As far as I understand it, the following message is important: Unsupported platform/architecture combination: linux/aarch64

But I don't understand that, because my chromedriver is definitely suitable:
xx@raspberrypi:~/.local/share/undetected_chromedriver/chromedriver_copy $ file chromedriver
`chromedriver: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=7df8916a45e29b6f80a1cd4dcbcf15fe06f9c97e, stripped`

Do any of you have experience with the Raspberry Pi, or perhaps see the error I'm not recognizing?
I would be very grateful for any help.

### Copy and paste your error

2024-10-17 21:03:46,793 [DEBUG] in __init__
2024-10-17 21:03:47,703 [ERROR] 
Traceback (most recent call last):
  File "/home/xx/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 67, in _binary_paths
    output = SeleniumManager().binary_paths(self._to_args())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 47, in binary_paths
    args = [str(self._get_binary())] + args
                ^^^^^^^^^^^^^^^^^^
  File "/home/xx/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 94, in _get_binary
    raise WebDriverException(f"Unsupported platform/architecture combination: {sys.platform}/{arch}")
selenium.common.exceptions.WebDriverException: Message: Unsupported platform/architecture combination: linux/aarch64

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xx/Skripte/MS-Rewards-Farmer/main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/Skripte/MS-Rewards-Farmer/main.py", line 235, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/Skripte/MS-Rewards-Farmer/src/browser.py", line 52, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/xx/Skripte/MS-Rewards-Farmer/src/browser.py", line 106, in browserSetup
    version = self.getChromeVersion()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/Skripte/MS-Rewards-Farmer/src/browser.py", line 223, in getChromeVersion
    driver = WebDriver(options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/xx/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 50, in __init__
    if finder.get_browser_path():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/xx/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

2024-10-17 21:03:47,706 [WARNING] config-private.yaml doesn't exist
2024-10-17 21:03:47,706 [DEBUG] No urls found, not sending notification
2024-10-17 21:03:47,706 [INFO] [POINTS] Data saved for the next day.

### Screenshots

none

### Value of dashboard variable

none

**Comment by zubtr** [comment]
Hola yo lo estoy usando en orangepi zero 3 de 4 GB de RAM. Y me funciona perfectamente. Para ello uso docker.

**Comment by cal4** [comment]
Is `chromedriver` on your `PATH` i.e. https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/#use-the-path-environment-variable?

**Comment by 28Black** [comment]
> Is `chromedriver` on your `PATH` i.e. https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/#use-the-path-environment-variable?

Hi cal4, thank you for helping me out! 👍 highly appreciate it!
Yes, that's what I also found in the troubleshooting section. The original chromedriver is located in `:/usr/bin`. According to what I've found, we need to copy it to the user folder `/home/xx/.local/share/undetected_chromedriver/chromedriver_copy` for uc/selenium to be able to patch it. 

I've double checked that it's in PATH:
`xx@raspberrypi:~ $ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/xx/.local/share/undetected_chromedriver/chromedriver_copy`

I've carefully read [this](https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues/361#issuecomment-1752098912) and [this](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/727#issuecomment-1216199477), but it just won't work. I have the feeling that the driver_executable_path is not correctly handed over the selenium/uc.

**Comment by 28Black** [comment]
I managed to get the bot running on my Pi 5! 🥳 

After another session of trial and error, I not only consulted internet sources, but also asked a “well-known” AI for ideas and support. In fact, there is no need to change browser.py (with `driver_executable_path=`), as stated in the issue threads I mentioned earlier (see links above). So, for those who may face the same issue, here is the solution:
 
> Note: I'm assuming here that you have already installed the bot including its requirements (in a venv). Change YOURNAME to your username.

- install chromedriver (`sudo apt install chromium-chromedriver`) and copy it to the user area (`cp /usr/bin/chromedriver /home/YOURNAME/.local/share/undetected_chromedriver/chromedriver_copy`)
- Add to PATH: Edit the file ~/.bashrc with a text editor or nano (`nano ~/.bashrc` ) by adding the following line at the end of the file: `export PATH="$PATH:/home/YOURNAME/.local/share/undetected_chromedriver/chromedriver_copy"`. Save that and reload the changes with `source ~/.bashrc` (you can check it with `echo $PATH`)
- navigate to the venv directory, e.g. `/home/YOURNAME/skripts/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/common` and open up the file `driver_finder.py` with **Geany**, for example
- search for `def __init__(self, service: Service, options: BaseOptions) -> None:` (at the time of writing line 36) and edit _underneath it_ `self._paths = ` (at the time of writing line 39) with the path to your copied chromedriver **file**. It should look like this:
`self._paths = {"driver_path": "/home/YOURNAME/.local/share/undetected_chromedriver/chromedriver_copy/chromedriver", "browser_path": ""}`
- save and you're done! 

The bot should start normally now. Selenium directs UC now correctly to the given aarch64 chromedriver, which it patches without trying to download an unsupported one. The patched chromedriver ('undetected_chromedriver') should now be located in the folder `/home/YOURNAME/.local/share/undetected_chromedriver`. Cheers.

**Comment by RikiCatte** [comment]
Hi! Until a few days ago this fix was working. But now I'm struggling with this error: 
```
2025-03-01 18:53:53,072 [INFO] ********************xxxxxxxxxxxx********************
2025-03-01 18:53:53,073 [DEBUG] in __init__
2025-03-01 18:53:53,221 [ERROR] 
Traceback (most recent call last):
  File "/home/riki/MS-Rewards-Farmer/main.py", line 32, in main
    earned_points = executeBot(currentAccount)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer/main.py", line 145, in executeBot
    with Browser(mobile=False, account=currentAccount) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer/src/browser.py", line 52, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer/src/browser.py", line 122, in browserSetup
    version = self.getChromeVersion()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer/src/browser.py", line 255, in getChromeVersion
    driver = WebDriver(options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 113, in start
    self.assert_process_still_running()
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 126, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/riki/.local/share/undetected_chromedriver/chromedriver_copy unexpectedly exited. Status code was: 1

2025-03-01 18:53:53,266 [INFO] [POINTS] Data saved for the next day.
```

I tried to update chromedriver through standard apt install and also from [here](https://github.com/electron/electron) (more frequently updated than standard chromedriver apt library) and also chromium but the error persist.

@28Black Are you experiencing the same problem? I'm on raspberry pi 5, **I'm in develop branch** because the known Google Trends issue was fixed there

**Comment by 28Black** [comment]
Hi @RikiCatte, I'll take a look this evening.
Recently I got quite some messages, so I might share my heavily modified searches.py based on current master branch (with adjustments to utils.py and browser.py). Develop branch raised more problems for me then it solved (naturally).

Your issue is new to me, it still works on my end, but I'll try to help you later.

**Comment by RikiCatte** [comment]
@28Black Thank you for the feedback!! If you aren't encountering this issue could you please share the code? Probably this is the fastest solution

**Comment by 28Black** [comment]
> [@28Black](https://github.com/28Black) Thank you for the feedback!! If you aren't encountering this issue could you please share the code? Probably this is the fastest solution

Just done, you can find it in #270 
Code is at the bottom for searches.py, browser.py and utils.py. It's for master branch, so replace the file there and not in your dev branch download!
Which language are you using? We need to make an adjustment if its non latin charset, eg asian, russian, etc.

**Comment by RikiCatte** [comment]
@28Black Great thank you! I'll try it as soon as I can. The language is italian so i should not have problems.

**Comment by RikiCatte** [comment]
Hi @28Black I'm here again :(. I tried your modified version of the code but the error persists: 

```
2025-03-04 22:50:19,157 [INFO] ********************riccardocatelani2005@gmail.com********************
2025-03-04 22:50:19,157 [DEBUG] in __init__
2025-03-04 22:50:19,630 [ERROR]
Traceback (most recent call last):
  File "/home/riki/MS-Rewards-Farmer-1.1.0-MOD/MS-Rewards-Farmer/main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer-1.1.0-MOD/MS-Rewards-Farmer/main.py", line 235, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer-1.1.0-MOD/MS-Rewards-Farmer/src/browser.py", line 53, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer-1.1.0-MOD/MS-Rewards-Farmer/src/browser.py", line 107, in browserSetup
    version = self.getChromeVersion()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer-1.1.0-MOD/MS-Rewards-Farmer/src/browser.py", line 226, in getChromeVersion
    driver = WebDriver(options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 113, in start
    self.assert_process_still_running()
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 126, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/chromedriver unexpectedly exited. Status code was: 1

2025-03-04 22:50:19,633 [WARNING] config-private.yaml doesn't exist
2025-03-04 22:50:19,633 [DEBUG] No urls found, not sending notification
2025-03-04 22:50:19,676 [INFO] [POINTS] Data saved for the next day.
```

I tried to install/update chromium and chromedriver from the official apt repository (snap) with this command: `sudo apt install chromium-chromedriver` with this output: 
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium-chromedriver is already the newest version (2:1snap1-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
But nothing good happens. I found on the web that previously this issue could be caused by something broken in snapd. What `chromium-chromedriver` version do you have?

**Comment by RikiCatte** [comment]
Hi @28Black I'm here again :(. I tried your modified version of the code but the error persists: 

```
2025-03-04 22:50:19,157 [INFO] ********************xxxxxxxxxxxxxxxxxxxxxx********************
2025-03-04 22:50:19,157 [DEBUG] in __init__
2025-03-04 22:50:19,630 [ERROR]
Traceback (most recent call last):
  File "/home/riki/MS-Rewards-Farmer-1.1.0-MOD/MS-Rewards-Farmer/main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer-1.1.0-MOD/MS-Rewards-Farmer/main.py", line 235, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer-1.1.0-MOD/MS-Rewards-Farmer/src/browser.py", line 53, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer-1.1.0-MOD/MS-Rewards-Farmer/src/browser.py", line 107, in browserSetup
    version = self.getChromeVersion()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/MS-Rewards-Farmer-1.1.0-MOD/MS-Rewards-Farmer/src/browser.py", line 226, in getChromeVersion
    driver = WebDriver(options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 113, in start
    self.assert_process_still_running()
  File "/home/riki/venv/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 126, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/chromedriver unexpectedly exited. Status code was: 1

2025-03-04 22:50:19,633 [WARNING] config-private.yaml doesn't exist
2025-03-04 22:50:19,633 [DEBUG] No urls found, not sending notification
2025-03-04 22:50:19,676 [INFO] [POINTS] Data saved for the next day.
```

I tried to install/update chromium and chromedriver from the official apt repository (snap) with this command: `sudo apt install chromium-chromedriver` with this output: 
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium-chromedriver is already the newest version (2:1snap1-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
But nothing good happens. I found on the web that previously this issue could be caused by something broken in snapd. What `chromium-chromedriver` version do you have? My current python version is 3.12.3 (latest version with sudo apt install python)

**Comment by 28Black** [comment]
@RikiCatte Hi there, I'll take a closer look tomorrow, it's pretty late right now.
I'm pretty sure I have as latest apt version of python 3.11. Chromium and chromedriver should be 130.x if I remember correctly.
What I can see right now is that you haven't set the correct path to user folder with the copied chromedriver. It currently points to /usr/bin/chromedriver which won't work.

I'm pretty sure we can sort things out tomorrow and can get it working for you!

**Comment by 28Black** [comment]
Hi @RikiCatte, so you made some progress.
You said you're also on RPi5, are you on Raspberry Pi OS?
I'm pretty sure there's something messed up with chromium & chromedriver. Are they on the exactly same version?
Are you running the Skript with chromium in headless mode (not recommended since your account may get flagged/banned rather quickly)?
Do you have an additional SD card to test in a clean environment?

**Comment by RikiCatte** [comment]
Hi @28Black, yes I'm on Pi 5 but in ubuntu server (24.04 LTS). Yes, chromedriver and chromium are compatible but I'm still receiving the error, yes I'm running the farmer in headless mode (without GUI). I could try to fresh install ubuntu server on hypervisor or similar and test it out (although the differences between amd64 and arm64). Unfortunately I don't have a SD card big enough to contain and run a instance of ubuntu server so I'll try as i said before to create a VM and recreate the environment running on the Pi. At the moment I'm running the farmer on a Windows instance to not loose points :)

**Comment by 28Black** [comment]
Alright, unfortunately I can't test Ubuntu on my end right now.
However, the error log is quite clear. Selenium tries to use the standard user data dir which is currently in use.
So we can't either specify a dedicated one, change the Skript to create a new one (temp) each time, or simple not use the --user-data-dir argument. Selenium will then create a temp dir for every run on its own, which should be fine.
I'll see how we can change it as soon as I'm home and on my Pi.

**Comment by RikiCatte** [comment]
@28Black Yes, i cleaned the sessions folder and after a clean run it creates a folder named with my email inside sessions folder

**Comment by 28Black** [comment]
Ok, interesting. Can you try not to run the script with the headless argument?

**Comment by RikiCatte** [comment]
I usually run the script without specifying the headless argument (so the default is `true` so without browser UI). Anyway i run it now with argument -v (with browser UI) and it shows up the same error

**Comment by 28Black** [comment]
@RikiCatte After some testing around I was able to reproduce the exact same error you had the last time. It happens to me if I simulate running it through a wrapper script via cron.. 

How exactly (!) are you executing the script?

**Comment by RikiCatte** [comment]
@28Black Nice! Yesterday, to get the last error I firstly became root with `sudo su`. Then I activated python env with `source ~/venv/bin/activate`. Then I moved to the farmer folder and finally I prompted `python main.py` to run the script.

**Comment by RikiCatte** [comment]
@28Black Pretty funny, I replicated the same ubuntu server environent on a hyper-v VM and everything runs smooth

**Comment by 28Black** [comment]
@RikiCatte 
That's what I thought. Can you try to start the script without superuser rights? 

I have no idea how it behaves with your Ubuntu distro. Actually, apt should use the appropriate architecture. Something is wrong. May I ask why you don't use raspberry pi OS? As far as I know, it is much better optimized for the pi.

**Comment by RikiCatte** [comment]
@28Black If I run the script in adm64 VM without root perms the execution stops and throws an error, this error says that the script could not access `/logs/activity.log` file. If I run the script with root perms there are no problems.
I chose Ubuntu server as OS because it is focused to host server applications and it has LTS updates.

**Comment by RikiCatte** [comment]
Don't worry! Thank you anyway for your time. I think that is a temporary error, in the meantime I'll run the script on a Windows machine.
