### ISSUE TITLE
This version of ChromeDriver only supports Chrome version xxx

### ISSUE THREAD

**Issue by FunnyPocketBook** [klept0/MS-Rewards-Farmer#218]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

develop

### Commit

ff3b02d

### Describe the bug

OS: Windows 11 22631.4391

I forgot to turn off auto-update for my Chrome so it got updated to 130.0.6723.69. The chromedriver only supports up to v128 and I don't know how to downgrade my Chrome or how to update the used chromedriver

### Copy and paste your error

https://gist.github.com/FunnyPocketBook/f028da7f2092c331f78d38faaac9b6fb

### Screenshots

browser not starting

### Value of dashboard variable

https://gist.github.com/FunnyPocketBook/f7fed7500593740818d9e8e3ae5e112e

**Comment by klept0** [comment]
https://googlechromelabs.github.io/chrome-for-testing/

**Comment by FunnyPocketBook** [comment]
Thanks for the link! Sorry for the trivial question, but where do I set the chromedriver path now?

**Comment by cal4** [comment]
Where you decided to put the download, see https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/#use-the-path-environment-variable for how to make it so it's picked up
