### ISSUE TITLE
Stuck on [DEBUG] in __init__

### ISSUE THREAD

**Issue by ruisuantonio** [klept0/MS-Rewards-Farmer#220]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

24a63e4

### Describe the bug

Every time that i try to execute MS Rewards Farmer, it freeze at [DEBUG] in __init__

2024-10-31 22:32:29,482 [INFO] ********************censured@spark.com********************
2024-10-31 22:32:29,483 [DEBUG] in __init__

### Copy and paste your error

2024-10-31 22:32:29,482 [INFO] ********************censured@spark.com********************
2024-10-31 22:26:51,451 [DEBUG] in __init__
* no error provided at all *

### Screenshots

none

### Value of dashboard variable

none

**Comment by ruisuantonio** [comment]
another bug:

https://gist.github.com/ruisuantonio/8d612d684ee164babbca2d468e317513

**Comment by Ices-Eyes** [comment]
Are you using it on Linux via ssh? If so, try to enable x11 forwarding on the session

**Comment by ruisuantonio** [comment]
> Are you using it on Linux via ssh? If so, try to enable x11 forwarding on the session

i was using windows, the problem was an update that firewall blocked connections made by automation
