### ISSUE TITLE
Issue with Search Bing Mobile

### ISSUE THREAD

**Issue by radiandedy** [klept0/MS-Rewards-Farmer#23]
After finish running the script when i check the account the mobile search points is missing like 40 point, is there any fix for this like checking the point again after finish search bing or make the search count to 25 or 30 ? as for now i running the script again to check the missing point.

In the script it says all 20 search has been done but when check manually it missing some point.

**Comment by klept0** [comment]
Base mobile searches for most US accounts are 20 - if your location provides more then you can make the change in your code as it will be easier for you to test your local limits.
