### ISSUE TITLE
invalid email

### ISSUE THREAD

**Issue by vedantakbari** [klept0/MS-Rewards-Farmer#235]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

?

### Describe the bug

 Invalid email: Your Email, skipping this account
email is valid

### Copy and paste your error

 Invalid email: Your Email, skipping this account

### Screenshots

vv

### Value of dashboard variable

vv

**Comment by klept0** [comment]
Closing due to lack of info - provide the information requested if you need assistance

**Comment by vedantakbari** [comment]
what is the dashboard var?
