### ISSUE TITLE
Crash during login on rewards.bing.com/signin-oidc

### ISSUE THREAD

**Issue by Guido30** [klept0/MS-Rewards-Farmer#236]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

develop

### Commit

6511198664ab7fca1489cdabf46e14f873f75b1b

### Describe the bug

Since today running the script crashes during the login phase, right before the crash the browser shows the page rewards.bing.com/signin-oidc with error HTTP 500, tried on multiple accounts, i also tried running an older version of the script, specifically commit 5ebddb72b7a3aaf2a380f25988de2795769a8d6e and it works just fine
EDIT: my bad the older version has the same issue i just forgot i had manually edited the url while the script was running

### Copy and paste your error

2024-12-06 11:12:04,571 [INFO] [LOGIN] Already logged-in
2024-12-06 11:12:41,462 [ERROR]
Traceback (most recent call last):
  File "C:\Repositories\MS-Rewards-Farmer\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\MS-Rewards-Farmer\main.py", line 237, in executeBot
    startingPoints = utils.getAccountPoints()
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\MS-Rewards-Farmer\src\utils.py", line 171, in getAccountPoints
    return self.getDashboardData()["userStatus"]["availablePoints"]
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\MS-Rewards-Farmer\src\utils.py", line 127, in getDashboardData
    self.goToRewards()
  File "C:\Repositories\MS-Rewards-Farmer\src\utils.py", line 114, in goToRewards
    self.webdriver.current_url == REWARDS_URL
AssertionError: https://rewards.bing.com/signin-oidc https://rewards.bing.com/

### Screenshots

.

### Value of dashboard variable

.

**Comment by Ices-Eyes** [comment]
Same here from today, unfortunately

**Comment by Ices-Eyes** [comment]
It seems today is working again...

**Comment by Guido30** [comment]
> It seems today is working again...

Same here, lets see if it keeps working for some time ill close the issue
