### ISSUE TITLE
Punch Card not working

### ISSUE THREAD

**Issue by radiandedy** [klept0/MS-Rewards-Farmer#29]
Hello,

there a issue with punch card script, it only open the page but didnt click any link on the punch card. so we didnt get any point from punch card.

in the script it only says this
[2023-11-14 00:12:08,477] [INFO] [PUNCH CARDS] Trying to complete the Punch Cards...
[2023-11-14 00:14:04,382] [INFO] [PUNCH CARDS] Completed the Punch Cards successfully !

but when i check manually it didnt click any punch card.

Thank you

**Comment by Ducky443747** [comment]
make sure you refreshed, and also try running it with the argument -v and see what is really going wrong for yourself.

**Comment by radiandedy** [comment]
the script only open this page and then a couple second later it close itself, the screenshot i include was example but in my account sometimes it work sometimes it dont, so im not sure what the problem.

![image](https://github.com/klept0/MS-Rewards-Farmer/assets/40633520/5b6ab8e9-830d-4b92-aa63-b94bf62a59a3)

**Comment by klept0** [comment]
If you try rerunning it and you are unable to get that one done - then I would do it manually then rerun the script and see if it proceeds from there. You *may* want to kill the sessions folder if you are seeing this on a regular basis so it will be a "fresh" profile
