### ISSUE TITLE
my fix doesnt work

### ISSUE THREAD

**Issue by CodeBanana69** [klept0/MS-Rewards-Farmer#37]
klept0, im still working on a fix for the list index. apparently ms patched it? sometimes it does more than 35 searches.

**Comment by klept0** [comment]
Your fix for closing out the app worked perfect - if you look at the code in my repo I integrated it with the fix for searches. Feel free to drop by the telegram group and chat if you have more questions!

**Comment by CodeBanana69** [comment]
> Your fix for closing out the app worked perfect - if you look at the code in my repo I integrated it with the fix for searches. Feel free to drop by the telegram group and chat if you have more questions!

ok thanks. i think i will start helping to apply fixes to this repo, instead of the orginal https://github.com/charlesbel/Microsoft-Rewards-Farmer.
