### ISSUE TITLE
[BUG] script hangs and WebDriverException when running without -v flag

### ISSUE THREAD

**Issue by oliverma-california** [klept0/MS-Rewards-Farmer#38]
When running in headless mode (i.e. not using -v flag), the script often hangs when trying to complete daily set or other tasks. It stays stuck until around 10 minutes when an error is thrown: [ERROR] WebDriverException: Message: disconnected: not connected to DevTools (failed to check if window was closed: disconnected: not connected to DevTools)

## Possible Fix
A similar problem happened once using the -v flag, and the webpage would not load because of ERR_HTTP2_PROTOCOL_ERROR. Not sure if that had anything to do with this bug though.

## Your Environment

* Version used: latest
* Environment name and version (e.g. Chrome ver): Chrome Version 119.0.6045.199 (Official Build) (arm64)
* Operating System and version: macOS Sonoma 14.1.1

**Comment by CodeBanana69** [comment]
same

**Comment by oliverma-california** [comment]
I have confirmed that this issue is not related to any issues with network or IP banning. If I run the script with -v flag, after successful login I am able to manually complete the daily set. Now it seems that the problem is most likely something to do with the webscraping.

**Comment by klept0** [comment]
From what I understand and checking with others - this can be caused by any of the following things..

- Outdated Software (Browser)
- Corrupted browser cache (Sessions folder)
- A/V or FIrewall
- Low Disk Space
