### ISSUE TITLE
[Feature Request] Mobile news points

### ISSUE THREAD

**Issue by Titaniumtown** [klept0/MS-Rewards-Farmer#39]
On the Bing app, you're able to earn up to 30 points a day for reading news article, 3 points per. Could this be added to the script? I don't know if a simple useragent change will register it as the app reading the article.

**Comment by klept0** [comment]
Already on the list in the readme of things to-do

**Comment by Titaniumtown** [comment]
Oh I am so sorry for the spam then! Keep up the great project!

**Comment by klept0** [comment]
no worries - join us on telegram if you ever have questions or want to shoot ideas around!

**Comment by Titaniumtown** [comment]
Oh, will do!
