### ISSUE TITLE
Microsoft Rewards Extension Request

### ISSUE THREAD

**Issue by Coder2195Text** [klept0/MS-Rewards-Farmer#44]
Is it possible to go to the chrome web store and install the extension from there through the script? Or load an crx file of the extension? I believe doing so unlocks the prediction game, and it is a extra 15 points I'm pretty sure

**Comment by CodeBanana69** [comment]
is this an extension? i think its a python script, idk about you tho

**Comment by klept0** [comment]
If you want a make a pull request for this feel free. I do not have the Chrome extension installed and it is on my account so I am not sure if that is what brings it up for people.

**Comment by klept0** [comment]
No plan on implementing this
