### ISSUE TITLE
[BUG]stuck in writing password 

### ISSUE THREAD

**Issue by lourok01** [klept0/MS-Rewards-Farmer#50]
2023-12-09 10:41:29,427 [INFO] Using default request storage
2023-12-09 10:41:29,612 [INFO] Created proxy listening on 127.0.0.1:55134
2023-12-09 10:41:29,613 [INFO] Using undetected_chromedriver
2023-12-09 10:41:32,288 [INFO] patching driver executable C:\Users\tomma\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2023-12-09 10:41:33,324 [INFO] Screen size: 1762x1461
2023-12-09 10:41:33,325 [INFO] Device size: 1707x1310
2023-12-09 10:41:33,529 [INFO] [LOGIN] Logging-in...
2023-12-09 10:41:39,439 [INFO] [LOGIN] Entering email...
2023-12-09 10:41:40,698 [INFO] [LOGIN] Writing password...

## Description
the bot get stuck in writing password but it's already writed the password

## Expected Behavior
the bot should see that the password has been written and should finish this step 
## Actual Behavior
the bot can't see that password writing has been completed

## Possible Fix
I've seen a solution where it goes by @idieli " All I did was change the hostname check on line 73 in src/login.py from
== "account.microsoft.com" to in ("account.microsoft.com", "rewards.bing.com").

This caused the call to self.utils.waitUntilVisible on line 78 to fail but I just replaced it with time.sleep(10) since it times out after 10 seconds anyway."
 but I can't find what's talking to line 73 and 78

**Comment by klept0** [comment]
This fix was tested and ended up being reverted as it caused other issues unfortunately

**Comment by lourok01** [comment]
> This fix was tested and ended up being reverted as it caused other issues unfortunately
> 
> Does your password contain special characters like " ' or \
> 
> If it does I can try to help narrow the issue down

Yes my password have special characters

**Comment by klept0** [comment]
That could be the issue - sendkeys does not like to send certain special chars. If you want to change the password to your account you can narrow that down to the issue else there might be something else. Make sure you delete whatever is in the sessions folder if you do change your password so you can do a clean test.

**Comment by idieli** [comment]
@klept0 What issues did the hostname change cause? Maybe it's something I can look into.

**Comment by klept0** [comment]
I think it had something to do with the time.sleep @ the bottom causing the issue. Im testing just the hostname version now locally to see if it helps the issue I was seeing.

**Comment by lourok01** [comment]
> I think it had something to do with the time.sleep @ the bottom causing the issue. Im testing just the hostname version now locally to see if it helps the issue I was seeing.

unfortunately time.sleep did not solve the writting password problem

**Comment by beenruuu** [comment]
Can you send the code to fix this? @lourok01 @klept0

**Comment by lourok01** [comment]
> Pouvez-vous envoyer le code pour résoudre ce problème ?@lourok01 @klept0
The issue occures if there is no session available and a new one gets created. After running the script a second time the session is recognized and it works fine. (Thanks @SgtSobieski)

**Comment by SgtSobieski** [comment]
Sorry, I deleted my comment as I noticed after some more test runs, that it can get stuck again. At the moment I use the repo from Charles directly which generally works and doesnt throw this error.
