### ISSUE TITLE
the 15 minute timer possible solutions thread

### ISSUE THREAD

**Issue by icescoop12** [klept0/MS-Rewards-Farmer#52]
## Description
not a bug as such but can you adjust the searching to do so many as now microsoft has introduced a cool down said to be 15 minute between every 3 searches to stop bots i suspect
see [here](https://www.reddit.com/r/MicrosoftRewards/comments/189cxl9/official_discussion_thread_recent_changes_to_the/?utm_source=share&utm_medium=web2x&context=3)
## Possible Fix
3 searches per account ,then we can just create windows task schedule to run the task every 20 mins or so to get around the cooldown?
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome ver):
* Operating System and version:

**Comment by icescoop12** [comment]
I think the bot will need a re-write to get around the 3-4 searches then 15 minute cooldown, maybe switches to choose amount of searches to do ,a switch to choose desktop or mobile and another switch to choose the daily sets ,promotions ect
then we run it on timers

**Comment by klept0** [comment]
You can edit any wait times in the script to handle your needs - read through the code and edit accordingly then test it out.

**Comment by icescoop12** [comment]
> You can edit any wait times in the script to handle your needs - read through the code and edit accordingly then test it out.

thanks ,not very good at python ,where would i edit for it to ignore how many searches/points left and for it to do 4 searches per run,thanks,or if possible take account of points and just do max 4 searches per run,as then will change to mobile,once desktop complete?

**Comment by caaaab** [comment]
This is what I made and I think it works. Fills the console every minute which I'm fine with but might get obnoxious for others. 

src/searches.py in the bingSearches function line 60

i = 0
        for word in search_terms:
            if i != 0 and i % 3 == 0:
                logging.info(
                    f"[BING] [PAUSE] Searched {i} times (multiple of 3), pausing for 15 minutes."
                )
                time.sleep(60)
                for i in range(14):
                    logging.info(
                        f"[BING] [PAUSE] {14-i} minutes remaining."
                    )
                    time.sleep(60)
                logging.info(
                    "[BING] [UNPAUSE] Resuming searches..."
                )
            i += 1

**Comment by caaaab** [comment]
You can try this fix in the bingSearches function line 60 (src/searches.py)
```
i = 0
        logging.info(
            f"[BING] Will approximately take {(numberOfSearches // 3) * 15} minutes (15 min. pause / 3 searches)"
        )
        for word in search_terms:
            if i != 0 and i % 3 == 0:
                logging.info(
                    f"[BING] [PAUSE] Searched {i} times (multiple of 3), pausing for 15 minutes."
                )
                time.sleep(60)
                for z in range(14):
                    logging.info(
                        f"[BING] [PAUSE] {14-z} minutes remaining."
                    )
                    time.sleep(60)
                logging.info(
                    "[BING] [UNPAUSE] Resuming searches..."
                )
            i += 1
```

**Comment by mgrimace** [comment]
> You can try this fix in the bingSearches function line 60 (src/searches.py)
> 
> ```
> i = 0
>         logging.info(
>             f"[BING] Will approximately take {(numberOfSearches // 3) * 15} minutes (15 min. pause / 3 searches)"
>         )
>         for word in search_terms:
>             if i != 0 and i % 3 == 0:
>                 logging.info(
>                     f"[BING] [PAUSE] Searched {i} times (multiple of 3), pausing for 15 minutes."
>                 )
>                 time.sleep(60)
>                 for z in range(14):
>                     logging.info(
>                         f"[BING] [PAUSE] {14-z} minutes remaining."
>                     )
>                     time.sleep(60)
>                 logging.info(
>                     "[BING] [UNPAUSE] Resuming searches..."
>                 )
>             i += 1
> ```

For the lay/copy-paste person, is it cut/paste this into searches.py at line 60 or replace the exising thing there?

**Comment by caaaab** [comment]
> > You can try this fix in the bingSearches function line 60 (src/searches.py)
> > ```
> > i = 0
> >         logging.info(
> >             f"[BING] Will approximately take {(numberOfSearches // 3) * 15} minutes (15 min. pause / 3 searches)"
> >         )
> >         for word in search_terms:
> >             if i != 0 and i % 3 == 0:
> >                 logging.info(
> >                     f"[BING] [PAUSE] Searched {i} times (multiple of 3), pausing for 15 minutes."
> >                 )
> >                 time.sleep(60)
> >                 for z in range(14):
> >                     logging.info(
> >                         f"[BING] [PAUSE] {14-z} minutes remaining."
> >                     )
> >                     time.sleep(60)
> >                 logging.info(
> >                     "[BING] [UNPAUSE] Resuming searches..."
> >                 )
> >             i += 1
> > ```
> 
> For the lay/copy-paste person, is it cut/paste this into searches.py at line 60 or replace the exising thing there?
replace @ line 60 so it should end up looking like this:
![image](https://github.com/klept0/MS-Rewards-Farmer/assets/72808210/f0df2a29-8230-471f-b726-c258f61ec56f)

**Comment by Coder2195Text** [comment]
It is actually every 4 searches, but I think if you have multiple accounts you can finish 1 account's "shift" and then do the next, and then wait for the first account to unexpired and then repeat the process. That way if you have multiple accounts u are doing all these searches in approx 5(1) hours and not 5(n) hours, where n is the number of accounts you have.

And I don't know about you guys but user agent no longer works with doing mobile searches.

**Comment by caaaab** [comment]
> It is actually every 4 searches, but I think if you have multiple accounts you can finish 1 account's "shift" and then do the next, and then wait for the first account to unexpired and then repeat the process. That way if you have multiple accounts u are doing all these searches in approx 5(1) hours and not 5(n) hours, where n is the number of accounts you have.
> 
> And I don't know about you guys but user agent no longer works with doing mobile searches.

I think the # of searches until cooldown is different for everyone depending on the region because, for me, it starts every 3. Just modify the code to fit your situation. My mobile searches also don't work anymore; should start a new issue for that.

**Comment by icescoop12** [comment]
anychance we can speed the searches up between the 15minutes, as just running this code:


> > > You can try this fix in the bingSearches function line 60 (src/searches.py)
> > > ```
> > > i = 0
> > >         logging.info(
> > >             f"[BING] Will approximately take {(numberOfSearches // 3) * 15} minutes (15 min. pause / 3 searches)"
> > >         )
> > >         for word in search_terms:
> > >             if i != 0 and i % 3 == 0:
> > >                 logging.info(
> > >                     f"[BING] [PAUSE] Searched {i} times (multiple of 3), pausing for 15 minutes."
> > >                 )
> > >                 time.sleep(60)
> > >                 for z in range(14):
> > >                     logging.info(
> > >                         f"[BING] [PAUSE] {14-z} minutes remaining."
> > >                     )
> > >                     time.sleep(60)
> > >                 logging.info(
> > >                     "[BING] [UNPAUSE] Resuming searches..."
> > >                 )
> > >             i += 1
> > > ```
> > 
> > 
> > For the lay/copy-paste person, is it cut/paste this into searches.py at line 60 or replace the exising thing there?
> 
> if you copy paste the whole thing replace @ line 60 so it should end up looking like this: ![image](https://private-user-images.githubusercontent.com/72808210/291748704-35e2d764-58e5-4a30-99db-71345ca3c5d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MzczNDUsIm5iZiI6MTcwODYzNzA0NSwicGF0aCI6Ii83MjgwODIxMC8yOTE3NDg3MDQtMzVlMmQ3NjQtNThlNS00YTMwLTk5ZGItNzEzNDVjYTNjNWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDIxMjQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYzQ3ZDc1YjkwOWNmM2FjZjgxMTQ1MmFmNmNjZWI4YmYwMjQyY2Y2OWM5ODJiOGNlZDhkZmJkNWU3MzE5NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cl5ue-Nfx8hwPBsDuzUY-dFoqxs5Fjx_amEQMv2uO7E) i just included the line before and after the new code starts so that it's easier to pinpoint where to put it

Is there anychance we can speed the searches up between the 15minutes, as just running this 1 line code @ line 63 code:

 if i % 4 == 0: time.sleep(900)

the 4 searches will complete in like 4 mins , compared to 12+ minutes with your solution, but your solution has the INFO prints?

thanks

**Comment by Ad-EmrysLee** [comment]
> anychance we can speed the searches up between the 15minutes, as just running this code:
> 
> > > > You can try this fix in the bingSearches function line 60 (src/searches.py)
> > > > ```
> > > > i = 0
> > > >         logging.info(
> > > >             f"[BING] Will approximately take {(numberOfSearches // 3) * 15} minutes (15 min. pause / 3 searches)"
> > > >         )
> > > >         for word in search_terms:
> > > >             if i != 0 and i % 3 == 0:
> > > >                 logging.info(
> > > >                     f"[BING] [PAUSE] Searched {i} times (multiple of 3), pausing for 15 minutes."
> > > >                 )
> > > >                 time.sleep(60)
> > > >                 for z in range(14):
> > > >                     logging.info(
> > > >                         f"[BING] [PAUSE] {14-z} minutes remaining."
> > > >                     )
> > > >                     time.sleep(60)
> > > >                 logging.info(
> > > >                     "[BING] [UNPAUSE] Resuming searches..."
> > > >                 )
> > > >             i += 1
> > > > ```
> > > 
> > > 
> > > For the lay/copy-paste person, is it cut/paste this into searches.py at line 60 or replace the exising thing there?
> > 
> > 
> > if you copy paste the whole thing replace @ line 60 so it should end up looking like this: ![image](https://private-user-images.githubusercontent.com/72808210/291748704-35e2d764-58e5-4a30-99db-71345ca3c5d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MzczNDUsIm5iZiI6MTcwODYzNzA0NSwicGF0aCI6Ii83MjgwODIxMC8yOTE3NDg3MDQtMzVlMmQ3NjQtNThlNS00YTMwLTk5ZGItNzEzNDVjYTNjNWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDIxMjQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYzQ3ZDc1YjkwOWNmM2FjZjgxMTQ1MmFmNmNjZWI4YmYwMjQyY2Y2OWM5ODJiOGNlZDhkZmJkNWU3MzE5NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cl5ue-Nfx8hwPBsDuzUY-dFoqxs5Fjx_amEQMv2uO7E) i just included the line before and after the new code starts so that it's easier to pinpoint where to put it
> 
> Is there anychance we can speed the searches up between the 15minutes, as just running this 1 line code @ line 63 code:
> 
> if i % 4 == 0: time.sleep(900)
> 
> the 4 searches will complete in like 4 mins , compared to 12+ minutes with your solution, but your solution has the INFO prints?
> 
> thanks

something like this?
```
            i += 1
            if i != 0 and i % 4 == 0:
                logging.info(
                    f"[BING] [PAUSE] Searched {i} times (multiple of 4), pausing for 20 minutes."
                )
                time.sleep(1200)  # Pause for 20 minutes (1200 seconds)
                logging.info(
                    "[BING] [UNPAUSE] Resuming searches..."
                )
```
