### ISSUE TITLE
[BUG] Versus Game is not working as expected

### ISSUE THREAD

**Issue by 666dsa666** [klept0/MS-Rewards-Farmer#57]
Versus Game is not working as expected

## Description
Since addition of Versus Game I'm having issue, while it does complete it it will return an error.
It may also coded badly enough to trigger something on server side

## Expected Behavior
Open the url, check if the games have been played, if not then play the game and go to the next section, otherwise go to the next section 

## Actual Behavior
Open the Url, Get a flyout url , Get an iframe url, open iframe url, loop 3 times using the same button, go to an error "JavascriptException: Message: javascript error: dashboard is not defined"

## Possible Fix
Temporary fix : 
Remove/Comment Line 236

Full fix : 
Stop using the iframe, Put a random on the buttonclick, correct the error - I'll try to do this myself in a few days

## Steps to Reproduce
Run the script

## Context
While those points may be a great bonus, the behaviour seems too risky.

## Your Environment

* Version used: Latest 
* Environment name and version (e.g. Chrome ver): Chrome 120.0.6099.130
* Operating System and version: W11

**Comment by klept0** [comment]
Closing as versus has been disabled - pull updated copy of files and issue should no longer occur
