### ISSUE TITLE
[BUG] cannot connect to chrome at 127.0.0.1:42925 from chrome not reachable and endless writting password 

### ISSUE THREAD

**Issue by lourok01** [klept0/MS-Rewards-Farmer#60]
cannot connect to chrome at 127.0.0.1:42925 from chrome not reachable and endless writting password 

## Description
when i don't have sessions folder the bot get stuck in writting password and when i relaunch the bot he say "cannot connect to chrome at 127.0.0.1:42925 from chrome not reachable

## Expected Behavior
after relaunch the bot i expected it work normaly and don't have chrome problem

## Actual Behavior
it get stuck after the session folder appears

* Version used:
*Version 120.0.6099.199 (e.g. Chrome ver):
* Operating System and version: Window 11

**Comment by lourok01** [comment]
my bad i found the issue

**Comment by oliverma-california** [comment]
what was the fix?
