### ISSUE TITLE
[BUG] hangs after logging in, stuck on "Writing password..."

### ISSUE THREAD

**Issue by oliverma-california** [klept0/MS-Rewards-Farmer#65]
## Description
The script freezes after "Writing password..." and eventually crashes (probably from disconnection). Running with -v shows that the browser is either stuck on the "Stay signed in?" page or the ms rewards home page. The pages are fully functional, the script just doesn't do anything.

## Your Environment

* Version used: latest as of 1/24/2024
* Environment name and version (e.g. Chrome ver): Version 121.0.6167.85 (Official Build) (arm64)
* Operating System and version: macOS 14.2.1

**Comment by TheAntic** [comment]
I am having this issue as well
