### ISSUE TITLE
[BUG] Desktop Searches Error

### ISSUE THREAD

**Issue by SgtSobieski** [klept0/MS-Rewards-Farmer#68]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

The Desktop searches arent completed with the following error message. I have the country and language code -fr set. Seems not to happen on other countries.

### Copy and paste your error

2024-02-02 09:08:10,037 [ERROR] JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\xxx\main.py", line 47, in main
    earned_points = executeBot(currentAccount, notifier, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xxx\main.py", line 249, in executeBot
    accountPointsCounter = Searches(desktopBrowser).bingSearches(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xxx\src\searches.py", line 61, in bingSearches
    search_terms = self.getGoogleTrends(numberOfSearches)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xxx\src\searches.py", line 31, in getGoogleTrends
    trends = json.loads(r.text[6:])
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xxx\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xxx\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\xxx\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Screenshots

![image](https://github.com/klept0/MS-Rewards-Farmer/assets/125480018/77be589f-cbf3-445a-9c66-59a2ad75346f)

### Value of dashboard variable

-

**Comment by klept0** [comment]
I can't duplicate this and neither can my tester - did you grab updated files from the repo or was this something new that happened?

**Comment by SgtSobieski** [comment]
Yes its happening on two seperate repositories with the newest version. I have that error only on an account working in France and one in the UK.

**Comment by he-sb** [comment]
Same issue when I set `--geo` flag to `CN`, it seems that the URL in [this line](https://github.com/klept0/MS-Rewards-Farmer/blob/7eeff19e01ccc80276d6f387250e4854a53dd432/src/searches.py#L29) is `https://trends.google.com/trends/api/dailytrends?hl=zh&ed=20240205&geo=CN&ns=15`, which always gets 400 error respond.

I test the google trends api, and it appears that language is irrelevant, only region matters. Some paticular region like `CN` or `UK` can't get right respond.

**Comment by SgtSobieski** [comment]
I just noticed two things which wil maybe also help somebody:
1. The region after -g has to be written in uppercase.
2. By checking (e.g.: https://trends.google.de/trends/?geo=GB) you can verify if you wrote the correct region. I used UK instead of GB in that instance.

Generally you can enter the language (hl=???) and region (geo=???) into this link and try it in the browser. If a json file is being downloaded its working: https://trends.google.com/trends/api/dailytrends?hl=uk&ed=20240220&geo=GB&ns=15 
This is used in [searches.py](https://searches.py/) line 29.
