### ISSUE TITLE
Stuck on "trying to complete the daily set..."

### ISSUE THREAD

**Issue by leem919** [klept0/MS-Rewards-Farmer#7]
The bot will login, display how many points I have, then get stuck on the microsoft rewards main page.

**Comment by klept0** [comment]
Are you running this in verbose mode or have anymore information to provide?

**Comment by klept0** [comment]
It appears as though others are having issues like this as well which is due to their IP being soft banned - if you are still having issues after trying another internet connection please re-open this issue.

**Comment by leem919** [comment]
I tried running in verbose mode, but got no other errors. I'm still having this issue, and I can also gain points manually on my home network, so I don't think I'm IP banned.

**Comment by klept0** [comment]
Yes it looks like you need to grab all installed packages then update them - this seems to have resolved the issue for others as well
