### ISSUE TITLE
[BUG] Are proxies being blocked?

### ISSUE THREAD

**Issue by icescoop12** [klept0/MS-Rewards-Farmer#70]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

cant seem to login via a proxy from the same country
never had these issues before,is microsoft blocking proxy connections to paid proxy services?

### Copy and paste your error

na

### Screenshots

na

### Value of dashboard variable

na

**Comment by DeanAmiridis** [comment]
It is not possible that a proxy being blocked is anything related to the script other than general use. 

_Similar to bringing your car to the dealership for service because you ran out of gas._

**Comment by icescoop12** [comment]
its completely touch and go now with a proxy using debian chromium 121,as getting a lot of hanging and errors
do you think its the proxy side?
