### ISSUE TITLE
Geo flag unnecessary

### ISSUE THREAD

**Issue by LtCMDstone** [klept0/MS-Rewards-Farmer#9]
Thanks for the further development of the bot!
I'm tinkering around to get it running stable in a Docker Enviroment and it suddenly crashed today after the "more promotion" I was digging deeper into the code and found out that the geo location flag isn't used as I can see.
e.g.
```
self.localeLang, self.localeGeo = self.getCCodeLang(args.lang, args.geo)
...
...
options.add_argument(f"--lang={self.localeLang}")
```

**Comment by klept0** [comment]
Try commenting it out and see if your Docker adventure works - I don't use it so I will let you do your tinkering there.

**Comment by LtCMDstone** [comment]
Yeah my Docker adventure runs stable since 3 days now 😄 at the moment as private repo, but after writing some readme stuff I will open it up for everyone. 
Regarding the geo flag I just wanted to mention it so you/we can clean it up to keep the code clean. 😉

**Comment by klept0** [comment]
Please feel free to do a PR that removes it - this was in the original one but I am unsure of anyone who uses it and we can make it optional going forward if needed. If you would ever like to chat about anything you can reach out to me on Telegram or Discord for easier conversations.

**Comment by LtCMDstone** [comment]
Alright, will have a look tomorrow or so 😁
Yeah would be cool, python is not my first and favorite language but willing to learn new stuff!
So maybe we can push the bot more forward, also my docker repo is now public if you're interested.also one question, why did you removed the discord and telegram json files? Another idea?

**Comment by klept0** [comment]
They were supposed to go to the beta repo branch but ended up in master as I was trying to do something. I’m not sure if it will work as I intended but it was intended to go there.

**Comment by LtCMDstone** [comment]
Ah ok I understand.
My suggestion would be to put the configuration into the already existing account.json, so it also could be account independent 😁

**Comment by klept0** [comment]
The geo flag is used in the /src/browser.py - not sure if it conflicts with what you are using but it does set the initial language when searching etc

**Comment by LtCMDstone** [comment]
Yeah that's half true 😄 it sets the language later but not the geo.
```
def browserSetup(
        self,
    ) -> WebDriver:
        options = webdriver.ChromeOptions()
        options.headless = self.headless
        options.add_argument(f"--lang={self.localeLang}") <----
        options.add_argument("--log-level=3")

        options.add_argument("--ignore-certificate-errors")
        options.add_argument("--ignore-certificate-errors-spki-list")
        options.add_argument("--ignore-ssl-errors")
```

so maybe we don't really need it or we add the geo to the browser 😃

**Comment by LtCMDstone** [comment]
Also I have found out that the "--lang" flag isn't used by chrome anymore
https://bugs.chromium.org/p/chromium/issues/detail?id=15359
I've tested some things.

To change chromes language it need a env variable named "LANG" like LANG=de
and then to change the websites language chrome need to be started with the flag "--accept-lang" like --accept-lang=de
https://peter.sh/experiments/chromium-command-line-switches/#accept-lang

Maybe you can double check by time 😄 

en_en
<img src="https://github.com/klept0/MS-Rewards-Farmer/assets/25282375/b032b30c-6e98-4282-97cb-418f4b49db2c" width="500" />

de_de
<img src="https://github.com/klept0/MS-Rewards-Farmer/assets/25282375/b309c11d-7898-4560-bdd4-8023ce1043d1" width="500" />

de_en
<img src="https://github.com/klept0/MS-Rewards-Farmer/assets/25282375/b5da3007-ffa6-40a2-a42d-691dd4223cc9" width="500" />

en_de
<img src="https://github.com/klept0/MS-Rewards-Farmer/assets/25282375/c9a7f3cf-5fe2-434b-9724-5c018155e8b3)" width="500" />

**Comment by klept0** [comment]
Did you do a PR to remove/replace or did we want to bypass this and close out the issue?

**Comment by LtCMDstone** [comment]
Not yet, hope to get time on the weekend for this :)
