### ISSUE TITLE
[BUG] Stuck at Logging in - not filing in MS login info...

### ISSUE THREAD

**Issue by marco97pa** [klept0/MS-Rewards-Farmer#90]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Starting about a week ago, the bot no longer works for me. In -v mode, I can see the Chrome browser launching the Microsoft Login page, but the bot fails to fill in the account information. Prior to this, the bot had worked for me for quite a while. Any idea what broke? 

I also tried to fill the username and password fields myself but I get a `TimeoutException`

### Copy and paste your error

![image](https://github.com/klept0/MS-Rewards-Farmer/assets/26876437/0457a5e1-3587-4801-a89e-54da571fb00d)

### Screenshots

![image](https://github.com/klept0/MS-Rewards-Farmer/assets/26876437/c0151b3c-2ebf-4ffa-9d70-4ea0126e2b27)

### Value of dashboard variable

https://gist.github.com/shopbuy11/a8417970aaa4a3a98621ef9afdb7602f

**Comment by klept0** [comment]
I'm not close to a machine but if you go to login.py and search for time.sleep around the top half of the file you can change those to longer periods and then manually login to test

**Comment by marco97pa** [comment]
I did a quick test slowing down times of username login but it didn't work

**Comment by klept0** [comment]
Can you login to the account normally from another browser?

**Comment by marco97pa** [comment]
yes, without issues

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by klept0** [comment]
Delete the contents of the sessions folder and try again if you have not done that. I can try and help troubleshoot later when I am back in front of a computer

**Comment by Lean1003** [comment]
you can try using -v and manually logging in yourself and it doesnt have to login next time

**Comment by marco97pa** [comment]
> you can try using -v and manually logging in yourself and it doesnt have to login next time

As I said in the bug report "I also tried to fill the username and password fields myself but I get a TimeoutException"

**Comment by ninetales58** [comment]
Try on a other laptop or os, if that doesnt work, uninstall and reinstall all dependencies.
