### ISSUE TITLE
[BUG] errors after "more promos"

### ISSUE THREAD

**Issue by SteveeeeeS** [klept0/MS-Rewards-Farmer#93]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Error after more promos section

### Copy and paste your error

2024-04-26 17:01:09,471 [WARNING] Error occurred: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.91)
Stacktrace:
        GetHandleVerifier [0x003AC113+48259]
        (No symbol) [0x0033CA41]
        (No symbol) [0x00230A17]
        (No symbol) [0x0020E02B]
        (No symbol) [0x0029742E]
        (No symbol) [0x002A9476]
        (No symbol) [0x00290B36]
        (No symbol) [0x0026570D]
        (No symbol) [0x002662CD]
        GetHandleVerifier [0x00666533+2908323]
        GetHandleVerifier [0x006A3B4B+3159739]
        GetHandleVerifier [0x0044505B+674763]
        GetHandleVerifier [0x0044B21C+699788]
        (No symbol) [0x00346244]
        (No symbol) [0x00342298]
        (No symbol) [0x0034242C]
        (No symbol) [0x00334BB0]
        BaseThreadInitThunk [0x75F87BA9+25]
        RtlInitializeExceptionChain [0x77C9BB9B+107]
        RtlClearBits [0x77C9BB1F+191]

### Screenshots

![Untitled](https://github.com/klept0/MS-Rewards-Farmer/assets/100130310/44249a76-f1da-4530-ba47-d6caac99ed35)

### Value of dashboard variable

https://gist.github.com/SteveeeeeS/199799b712446a3be0a001beb8283264

**Comment by klept0** [comment]
When you are running this are you seeing promos not completed or are they all done?

**Comment by SteveeeeeS** [comment]
It gives the error everything. It's started opening chrome randomly. Sometimes it may get a bit further but last 3 days or so its failed with this



Stephen



-------- Original message --------
From: klept0 ***@***.***>
Date: 26/04/2024 18:18 (GMT+00:00)
To: klept0/MS-Rewards-Farmer ***@***.***>
Cc: SteveeeeeS ***@***.***>, Author ***@***.***>
Subject: Re: [klept0/MS-Rewards-Farmer] [BUG] errors after "more promos" (Issue #93)


When you are running this are you seeing promos not completed or are they all done?

**Comment by SteveeeeeS** [comment]
2024-04-26 21:39:57,217 [WARNING] Error occurred: HTTPSConnectionPool(host='edgeupdates.microsoft.com', port=443): Max retries exceeded with url: /api/products (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))). Retrying...

**Comment by klept0** [comment]
Delete your sessions folder content and try again - that is not an issue with the script but an issue on your side.

**Comment by SteveeeeeS** [comment]
Didn't know I could do that. I'll give it a try and feedback. Thanks.



Stephen



-------- Original message --------
From: klept0 ***@***.***>
Date: 27/04/2024 07:40 (GMT+00:00)
To: klept0/MS-Rewards-Farmer ***@***.***>
Cc: SteveeeeeS ***@***.***>, Author ***@***.***>
Subject: Re: [klept0/MS-Rewards-Farmer] [BUG] errors after "more promos" (Issue #93)


Delete your sessions folder content and try again - that is not an issue with the script but an issue on your side.

**Comment by SteveeeeeS** [comment]
Is it worth clearing that folder (or particular folders within) on a semi regular basis?



-------- Original message --------
From: klept0 ***@***.***>
Date: 27/04/2024 07:40 (GMT+00:00)
To: klept0/MS-Rewards-Farmer ***@***.***>
Cc: SteveeeeeS ***@***.***>, Author ***@***.***>
Subject: Re: [klept0/MS-Rewards-Farmer] [BUG] errors after "more promos" (Issue #93)


Delete your sessions folder content and try again - that is not an issue with the script but an issue on your side.

**Comment by klept0** [comment]
Occasionally nuking the contents of that folder has resolved peoples issues - keep in mind you will have to login each time after you wipe that folder. If space is a concern you can see how large that folder is growing and delete if necessary as well.

**Comment by Kenneth-zh** [comment]
I encountered this when I ran the program on ubuntu with the latest chrome

**Comment by Kenneth-zh** [comment]
but seemingly deleting sessions file just simply fix it

**Comment by klept0** [comment]
Do you see the "blockage" if you are searching manually or only with the assistance of this script?

**Comment by SteveeeeeS** [comment]
Never had it manually using bing.

Just got error occurred. Message: no such window: target window already closed from unknown error: Web view not found

If anything I can do to help diagnosis let me know

Stephen



-------- Original message --------
From: klept0 ***@***.***>
Date: 29/04/2024 15:23 (GMT+00:00)
To: klept0/MS-Rewards-Farmer ***@***.***>
Cc: SteveeeeeS ***@***.***>, Author ***@***.***>
Subject: Re: [klept0/MS-Rewards-Farmer] [BUG] errors after "more promos" (Issue #93)


Do you see the "blockage" if you are searching manually or only with the assistance of this script?

**Comment by constantindjonkam** [comment]
It's definitely an issue. For the past few days I realized my pts weren't going up by much so today I manually ran it and it crashes at more promos multiple times. So I did the promos myself and I noticed that after completing one of them the ms reward site showed an error (page error, myb I forgot to screenshot). I think to bypass this all that's is needed is navigate back to ms rewards and continue the more promo thing when the error occurs. (Moreover, some of their quizzes are now many more questions that needs to be answered than before) 

After completing it myself today the script is working

**Comment by SteveeeeeS** [comment]
Yeah. Funny you say that. I "thought" when I manually did some question it went further that previously.
I clear seasions and it still fails. Tried deleting a few times



Stephen



-------- Original message --------
From: Constantin Djonkam ***@***.***>
Date: 30/04/2024 15:17 (GMT+00:00)
To: klept0/MS-Rewards-Farmer ***@***.***>
Cc: SteveeeeeS ***@***.***>, Author ***@***.***>
Subject: Re: [klept0/MS-Rewards-Farmer] [BUG] errors after "more promos" (Issue #93)


It's definitely an issue. For the past few days I realized my pts weren't going up by much so today I manually ran it and it crashes at more promos multiple times. So I did the promos myself and I noticed that after completing one of them the ms reward site showed an error (page error, myb I forgot to screenshot). I think to bypass this all that's is needed is navigate back to ms rewards and continue the more promo thing when the error occurs. (Moreover, some of their quizzes are now many more questions that needs to be answered than before)

After completing it myself today the script is working

**Comment by DarkDrake666** [comment]
where is the sessions folder and what is it because i cant find it anywhere online @klept0

**Comment by SteveeeeeS** [comment]
It's in your run from/install location



Stephen



-------- Original message --------
From: 1NTORT ***@***.***>
Date: 08/05/2024 17:11 (GMT+00:00)
To: klept0/MS-Rewards-Farmer ***@***.***>
Cc: SteveeeeeS ***@***.***>, Author ***@***.***>
Subject: Re: [klept0/MS-Rewards-Farmer] [BUG] errors after "more promos" (Issue #93)


where is the sessions folder and what is it because i cant find it anywhere online @klept0<https://github.com/klept0>

**Comment by DarkDrake666** [comment]
ohh sorry i didnt realise that was in there
